### ISSUE TITLE
get an error in python scripts

### ISSUE THREAD

**Issue by jkruseAUT** [baxter-flowers/kinect_2_server#1]
I tried a few things, but am stuck - how do I address the 'use setsockopt_string' error? just replacing setsockopt with setsockopt_string creates a lot more errors :)

self._socket_face.setsockopt(SUBSCRIBE, "face")

Traceback (most recent call last):
  File "C:/Users/jkruse/Python/VideoWall/client1.py", line 2, in <module>
    kinect = Kinect2Client("10.249.59.101")
  File "C:\Users\jkruse\AppData\Local\Programs\Python\Python35\lib\site-packages\kinect2\client.py", line 10, in __init__
    self.skeleton = SkeletonSubscriber(self._context, ip, skel_port, param_port)
  File "C:\Users\jkruse\AppData\Local\Programs\Python\Python35\lib\site-packages\kinect2\subscriber.py", line 86, in __init__
    self._socket_face.setsockopt(SUBSCRIBE, "face")
  File "zmq\backend\cython\socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq\backend\cython\socket.c:4610)
TypeError: unicode not allowed, use setsockopt_string

**Comment by ymollard** [comment]
I never tested this lib in Python 3. [This](http://pyzmq.readthedocs.io/en/latest/unicode.html) is the relevant explanation.
What's that errors with `setsockopt_string`?
